// RUN: mlir-link -split-input-file %s | FileCheck %s

//===----------------------------------------------------------------------===//
// Test: Cross-TU external declaration type mismatch resolution
//===----------------------------------------------------------------------===//
//
// When multiple translation units declare the same external function with
// different return types, the linker should:
//
//   1. Prefer the larger integer return type (e.g., i32 over i8)
//   2. Insert truncation at call sites that expect the smaller type
//
// This commonly occurs with CMake's CheckFunctionExists mechanism, which
// declares all probed functions as returning `char` (i8) regardless of
// their actual return type. For example:
//
//   // CheckFunctionExists.c (generated by CMake)
//   char getpid(void);  // Wrong! Should be pid_t (i32)
//
// Without this fix, the linker would create duplicate symbols or leave
// the wrong declaration, breaking calls from other translation units.
//===----------------------------------------------------------------------===//

// The call site expecting i8 should call the i32 version with truncation
// CHECK-LABEL: llvm.func @caller_expecting_i8() -> i8
// CHECK:         %[[CALL:.*]] = llvm.call @getpid() : () -> i32
// CHECK-NEXT:    %[[TRUNC:.*]] = llvm.trunc %[[CALL]] : i32 to i8
// CHECK-NEXT:    llvm.return %[[TRUNC]] : i8

// The canonical declaration should have the larger return type (i32)
// CHECK: llvm.func @getpid() -> i32

//===----------------------------------------------------------------------===//
// Module 1: Incorrect declaration (i8 return type) with call site
//===----------------------------------------------------------------------===//
// This simulates a TU that included CMake's CheckFunctionExists.c which
// declares getpid as returning char (i8).

llvm.func @getpid() -> i8

llvm.func @caller_expecting_i8() -> i8 {
  %0 = llvm.call @getpid() : () -> i8
  llvm.return %0 : i8
}

// -----

//===----------------------------------------------------------------------===//
// Module 2: Correct declaration (i32 return type)
//===----------------------------------------------------------------------===//
// This is the correct declaration as would appear in normal code.

llvm.func @getpid() -> i32
